CREATE DATABASE DogPhotosDb;
GO
USE DogPhotosDb;
GO
CREATE TABLE DogPhotos (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Breed NVARCHAR(100) NOT NULL,
    SubBreed NVARCHAR(100) NULL,
    ImageUrl NVARCHAR(500) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);